// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: trainer.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Trainer_CreateTrainer_FullMethodName = "/pb.trainer/CreateTrainer"
	Trainer_GetTrainer_FullMethodName    = "/pb.trainer/GetTrainer"
	Trainer_AddPokemon_FullMethodName    = "/pb.trainer/AddPokemon"
)

// TrainerClient is the client API for Trainer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrainerClient interface {
	CreateTrainer(ctx context.Context, in *CreateTrainerRequest, opts ...grpc.CallOption) (*CreateTrainerResponse, error)
	GetTrainer(ctx context.Context, in *GetTrainerRequest, opts ...grpc.CallOption) (*GetTrainerResponse, error)
	AddPokemon(ctx context.Context, in *AddPokemonRequest, opts ...grpc.CallOption) (*AddPokemonResponse, error)
}

type trainerClient struct {
	cc grpc.ClientConnInterface
}

func NewTrainerClient(cc grpc.ClientConnInterface) TrainerClient {
	return &trainerClient{cc}
}

func (c *trainerClient) CreateTrainer(ctx context.Context, in *CreateTrainerRequest, opts ...grpc.CallOption) (*CreateTrainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTrainerResponse)
	err := c.cc.Invoke(ctx, Trainer_CreateTrainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainerClient) GetTrainer(ctx context.Context, in *GetTrainerRequest, opts ...grpc.CallOption) (*GetTrainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrainerResponse)
	err := c.cc.Invoke(ctx, Trainer_GetTrainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trainerClient) AddPokemon(ctx context.Context, in *AddPokemonRequest, opts ...grpc.CallOption) (*AddPokemonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPokemonResponse)
	err := c.cc.Invoke(ctx, Trainer_AddPokemon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainerServer is the server API for Trainer service.
// All implementations must embed UnimplementedTrainerServer
// for forward compatibility.
type TrainerServer interface {
	CreateTrainer(context.Context, *CreateTrainerRequest) (*CreateTrainerResponse, error)
	GetTrainer(context.Context, *GetTrainerRequest) (*GetTrainerResponse, error)
	AddPokemon(context.Context, *AddPokemonRequest) (*AddPokemonResponse, error)
	mustEmbedUnimplementedTrainerServer()
}

// UnimplementedTrainerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrainerServer struct{}

func (UnimplementedTrainerServer) CreateTrainer(context.Context, *CreateTrainerRequest) (*CreateTrainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrainer not implemented")
}
func (UnimplementedTrainerServer) GetTrainer(context.Context, *GetTrainerRequest) (*GetTrainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrainer not implemented")
}
func (UnimplementedTrainerServer) AddPokemon(context.Context, *AddPokemonRequest) (*AddPokemonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPokemon not implemented")
}
func (UnimplementedTrainerServer) mustEmbedUnimplementedTrainerServer() {}
func (UnimplementedTrainerServer) testEmbeddedByValue()                 {}

// UnsafeTrainerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrainerServer will
// result in compilation errors.
type UnsafeTrainerServer interface {
	mustEmbedUnimplementedTrainerServer()
}

func RegisterTrainerServer(s grpc.ServiceRegistrar, srv TrainerServer) {
	// If the following call pancis, it indicates UnimplementedTrainerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Trainer_ServiceDesc, srv)
}

func _Trainer_CreateTrainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainerServer).CreateTrainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trainer_CreateTrainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainerServer).CreateTrainer(ctx, req.(*CreateTrainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trainer_GetTrainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainerServer).GetTrainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trainer_GetTrainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainerServer).GetTrainer(ctx, req.(*GetTrainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trainer_AddPokemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPokemonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainerServer).AddPokemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trainer_AddPokemon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainerServer).AddPokemon(ctx, req.(*AddPokemonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Trainer_ServiceDesc is the grpc.ServiceDesc for Trainer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Trainer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.trainer",
	HandlerType: (*TrainerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrainer",
			Handler:    _Trainer_CreateTrainer_Handler,
		},
		{
			MethodName: "GetTrainer",
			Handler:    _Trainer_GetTrainer_Handler,
		},
		{
			MethodName: "AddPokemon",
			Handler:    _Trainer_AddPokemon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trainer.proto",
}
