// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: trainer.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pokemon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Types         []string               `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pokemon) Reset() {
	*x = Pokemon{}
	mi := &file_trainer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pokemon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pokemon) ProtoMessage() {}

func (x *Pokemon) ProtoReflect() protoreflect.Message {
	mi := &file_trainer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pokemon.ProtoReflect.Descriptor instead.
func (*Pokemon) Descriptor() ([]byte, []int) {
	return file_trainer_proto_rawDescGZIP(), []int{0}
}

func (x *Pokemon) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pokemon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pokemon) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

type CreateTrainerRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FavoritePokemonType string                 `protobuf:"bytes,2,opt,name=favorite_pokemon_type,json=favoritePokemonType,proto3" json:"favorite_pokemon_type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateTrainerRequest) Reset() {
	*x = CreateTrainerRequest{}
	mi := &file_trainer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrainerRequest) ProtoMessage() {}

func (x *CreateTrainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trainer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrainerRequest.ProtoReflect.Descriptor instead.
func (*CreateTrainerRequest) Descriptor() ([]byte, []int) {
	return file_trainer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTrainerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTrainerRequest) GetFavoritePokemonType() string {
	if x != nil {
		return x.FavoritePokemonType
	}
	return ""
}

type CreateTrainerResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FavoritePokemonType string                 `protobuf:"bytes,3,opt,name=favorite_pokemon_type,json=favoritePokemonType,proto3" json:"favorite_pokemon_type,omitempty"`
	Pokemons            []*Pokemon             `protobuf:"bytes,4,rep,name=pokemons,proto3" json:"pokemons,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateTrainerResponse) Reset() {
	*x = CreateTrainerResponse{}
	mi := &file_trainer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrainerResponse) ProtoMessage() {}

func (x *CreateTrainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trainer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrainerResponse.ProtoReflect.Descriptor instead.
func (*CreateTrainerResponse) Descriptor() ([]byte, []int) {
	return file_trainer_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTrainerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTrainerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTrainerResponse) GetFavoritePokemonType() string {
	if x != nil {
		return x.FavoritePokemonType
	}
	return ""
}

func (x *CreateTrainerResponse) GetPokemons() []*Pokemon {
	if x != nil {
		return x.Pokemons
	}
	return nil
}

type GetTrainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrainerRequest) Reset() {
	*x = GetTrainerRequest{}
	mi := &file_trainer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainerRequest) ProtoMessage() {}

func (x *GetTrainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trainer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrainerRequest.ProtoReflect.Descriptor instead.
func (*GetTrainerRequest) Descriptor() ([]byte, []int) {
	return file_trainer_proto_rawDescGZIP(), []int{3}
}

func (x *GetTrainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTrainerResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FavoritePokemonType string                 `protobuf:"bytes,3,opt,name=favorite_pokemon_type,json=favoritePokemonType,proto3" json:"favorite_pokemon_type,omitempty"`
	Pokemons            []*Pokemon             `protobuf:"bytes,4,rep,name=pokemons,proto3" json:"pokemons,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetTrainerResponse) Reset() {
	*x = GetTrainerResponse{}
	mi := &file_trainer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainerResponse) ProtoMessage() {}

func (x *GetTrainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trainer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrainerResponse.ProtoReflect.Descriptor instead.
func (*GetTrainerResponse) Descriptor() ([]byte, []int) {
	return file_trainer_proto_rawDescGZIP(), []int{4}
}

func (x *GetTrainerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTrainerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTrainerResponse) GetFavoritePokemonType() string {
	if x != nil {
		return x.FavoritePokemonType
	}
	return ""
}

func (x *GetTrainerResponse) GetPokemons() []*Pokemon {
	if x != nil {
		return x.Pokemons
	}
	return nil
}

type AddPokemonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrainerId     string                 `protobuf:"bytes,1,opt,name=trainer_id,json=trainerId,proto3" json:"trainer_id,omitempty"`
	PokemonId     int32                  `protobuf:"varint,2,opt,name=pokemon_id,json=pokemonId,proto3" json:"pokemon_id,omitempty"`
	PokemonName   string                 `protobuf:"bytes,3,opt,name=pokemon_name,json=pokemonName,proto3" json:"pokemon_name,omitempty"`
	PokemonTypes  []string               `protobuf:"bytes,4,rep,name=pokemon_types,json=pokemonTypes,proto3" json:"pokemon_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPokemonRequest) Reset() {
	*x = AddPokemonRequest{}
	mi := &file_trainer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPokemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPokemonRequest) ProtoMessage() {}

func (x *AddPokemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trainer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPokemonRequest.ProtoReflect.Descriptor instead.
func (*AddPokemonRequest) Descriptor() ([]byte, []int) {
	return file_trainer_proto_rawDescGZIP(), []int{5}
}

func (x *AddPokemonRequest) GetTrainerId() string {
	if x != nil {
		return x.TrainerId
	}
	return ""
}

func (x *AddPokemonRequest) GetPokemonId() int32 {
	if x != nil {
		return x.PokemonId
	}
	return 0
}

func (x *AddPokemonRequest) GetPokemonName() string {
	if x != nil {
		return x.PokemonName
	}
	return ""
}

func (x *AddPokemonRequest) GetPokemonTypes() []string {
	if x != nil {
		return x.PokemonTypes
	}
	return nil
}

type AddPokemonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrainerId     string                 `protobuf:"bytes,1,opt,name=trainer_id,json=trainerId,proto3" json:"trainer_id,omitempty"`
	PokemonId     int32                  `protobuf:"varint,2,opt,name=pokemon_id,json=pokemonId,proto3" json:"pokemon_id,omitempty"`
	PokemonName   string                 `protobuf:"bytes,3,opt,name=pokemon_name,json=pokemonName,proto3" json:"pokemon_name,omitempty"`
	PokemonTypes  []string               `protobuf:"bytes,4,rep,name=pokemon_types,json=pokemonTypes,proto3" json:"pokemon_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPokemonResponse) Reset() {
	*x = AddPokemonResponse{}
	mi := &file_trainer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPokemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPokemonResponse) ProtoMessage() {}

func (x *AddPokemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trainer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPokemonResponse.ProtoReflect.Descriptor instead.
func (*AddPokemonResponse) Descriptor() ([]byte, []int) {
	return file_trainer_proto_rawDescGZIP(), []int{6}
}

func (x *AddPokemonResponse) GetTrainerId() string {
	if x != nil {
		return x.TrainerId
	}
	return ""
}

func (x *AddPokemonResponse) GetPokemonId() int32 {
	if x != nil {
		return x.PokemonId
	}
	return 0
}

func (x *AddPokemonResponse) GetPokemonName() string {
	if x != nil {
		return x.PokemonName
	}
	return ""
}

func (x *AddPokemonResponse) GetPokemonTypes() []string {
	if x != nil {
		return x.PokemonTypes
	}
	return nil
}

var File_trainer_proto protoreflect.FileDescriptor

const file_trainer_proto_rawDesc = "" +
	"\n" +
	"\rtrainer.proto\x12\x02pb\"C\n" +
	"\aPokemon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05types\x18\x03 \x03(\tR\x05types\"^\n" +
	"\x14CreateTrainerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x15favorite_pokemon_type\x18\x02 \x01(\tR\x13favoritePokemonType\"\x98\x01\n" +
	"\x15CreateTrainerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\x15favorite_pokemon_type\x18\x03 \x01(\tR\x13favoritePokemonType\x12'\n" +
	"\bpokemons\x18\x04 \x03(\v2\v.pb.PokemonR\bpokemons\"#\n" +
	"\x11GetTrainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x95\x01\n" +
	"\x12GetTrainerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\x15favorite_pokemon_type\x18\x03 \x01(\tR\x13favoritePokemonType\x12'\n" +
	"\bpokemons\x18\x04 \x03(\v2\v.pb.PokemonR\bpokemons\"\x99\x01\n" +
	"\x11AddPokemonRequest\x12\x1d\n" +
	"\n" +
	"trainer_id\x18\x01 \x01(\tR\ttrainerId\x12\x1d\n" +
	"\n" +
	"pokemon_id\x18\x02 \x01(\x05R\tpokemonId\x12!\n" +
	"\fpokemon_name\x18\x03 \x01(\tR\vpokemonName\x12#\n" +
	"\rpokemon_types\x18\x04 \x03(\tR\fpokemonTypes\"\x9a\x01\n" +
	"\x12AddPokemonResponse\x12\x1d\n" +
	"\n" +
	"trainer_id\x18\x01 \x01(\tR\ttrainerId\x12\x1d\n" +
	"\n" +
	"pokemon_id\x18\x02 \x01(\x05R\tpokemonId\x12!\n" +
	"\fpokemon_name\x18\x03 \x01(\tR\vpokemonName\x12#\n" +
	"\rpokemon_types\x18\x04 \x03(\tR\fpokemonTypes2\xcf\x01\n" +
	"\atrainer\x12F\n" +
	"\rCreateTrainer\x12\x18.pb.CreateTrainerRequest\x1a\x19.pb.CreateTrainerResponse\"\x00\x12=\n" +
	"\n" +
	"GetTrainer\x12\x15.pb.GetTrainerRequest\x1a\x16.pb.GetTrainerResponse\"\x00\x12=\n" +
	"\n" +
	"AddPokemon\x12\x15.pb.AddPokemonRequest\x1a\x16.pb.AddPokemonResponse\"\x00B\x17Z\x15trainer/internal/grpcb\x06proto3"

var (
	file_trainer_proto_rawDescOnce sync.Once
	file_trainer_proto_rawDescData []byte
)

func file_trainer_proto_rawDescGZIP() []byte {
	file_trainer_proto_rawDescOnce.Do(func() {
		file_trainer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trainer_proto_rawDesc), len(file_trainer_proto_rawDesc)))
	})
	return file_trainer_proto_rawDescData
}

var file_trainer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_trainer_proto_goTypes = []any{
	(*Pokemon)(nil),               // 0: pb.Pokemon
	(*CreateTrainerRequest)(nil),  // 1: pb.CreateTrainerRequest
	(*CreateTrainerResponse)(nil), // 2: pb.CreateTrainerResponse
	(*GetTrainerRequest)(nil),     // 3: pb.GetTrainerRequest
	(*GetTrainerResponse)(nil),    // 4: pb.GetTrainerResponse
	(*AddPokemonRequest)(nil),     // 5: pb.AddPokemonRequest
	(*AddPokemonResponse)(nil),    // 6: pb.AddPokemonResponse
}
var file_trainer_proto_depIdxs = []int32{
	0, // 0: pb.CreateTrainerResponse.pokemons:type_name -> pb.Pokemon
	0, // 1: pb.GetTrainerResponse.pokemons:type_name -> pb.Pokemon
	1, // 2: pb.trainer.CreateTrainer:input_type -> pb.CreateTrainerRequest
	3, // 3: pb.trainer.GetTrainer:input_type -> pb.GetTrainerRequest
	5, // 4: pb.trainer.AddPokemon:input_type -> pb.AddPokemonRequest
	2, // 5: pb.trainer.CreateTrainer:output_type -> pb.CreateTrainerResponse
	4, // 6: pb.trainer.GetTrainer:output_type -> pb.GetTrainerResponse
	6, // 7: pb.trainer.AddPokemon:output_type -> pb.AddPokemonResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_trainer_proto_init() }
func file_trainer_proto_init() {
	if File_trainer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trainer_proto_rawDesc), len(file_trainer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trainer_proto_goTypes,
		DependencyIndexes: file_trainer_proto_depIdxs,
		MessageInfos:      file_trainer_proto_msgTypes,
	}.Build()
	File_trainer_proto = out.File
	file_trainer_proto_goTypes = nil
	file_trainer_proto_depIdxs = nil
}
